Link python extensions against shared libawkward
If there is some mismatch between typeinfo symbols due to copies that
may appear due to static linking, this might fix it. Interestingly,
this instead turns 13 test failures into 171 test failures of the same
kind:

RuntimeError: missing boxer for Content subtype

This also removes "CXX_VISIBILITY_PRESET hidden" from libawkard
interface as it currently hides typeinfo symbols.